server:
  port: 3000
eureka:
  instance:
    hostname: eureka-server
    appname: 注册中心
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000